### ISSUE TITLE
Download Pdf

### ISSUE THREAD

**Issue by amisha2016** [GreatDevelopers/Certificate#12]
Download pdf option not working under the feature "Fill candidate details manually".

**Comment by singh1114** [comment]
@amisha2016 Explain furthur.

**Comment by amisha2016** [comment]
The above issue is solved.
I have explained it in my blog https://amisha2016.wordpress.com/2016/06/08/certificate-generation-system/
I have send the PR also.

**Comment by amisha2016** [comment]
No response yet. PR is also not merged.
@amarjeetkapoor1 
Whether you tried it or not.
