### ISSUE TITLE
static  setup path for "pclzip.lib.php"

### ISSUE THREAD

**Issue by SatinderpalSingh** [GreatDevelopers/Certificate#14]
Why the path at this point is pointing to /var/www/Certificate this may be vary from system to system. Please check it and correct it.

**Comment by amisha2016** [comment]
@SatinderpalSingh Will you describe more that where this absolute path is given. I mean in which file.

**Comment by SatinderpalSingh** [comment]
This was a very old issue and out of my memory, i will tell you after re-installation.

**Comment by dsdeeptisharma** [comment]
In this project, I found this path written in Readme.md file only.
<q>
cd /var/www/Certificate/library/zip/pclzip/
</q>
@SatinderpalSingh Is this the path you are talking about?

**Comment by mandeeps708** [comment]
That's no longer valid, I guess. So closing till re-encountered.
