### ISSUE TITLE
Certificate without image?

### ISSUE THREAD

**Issue by mandeeps708** [GreatDevelopers/Certificate#21]
Currently, there doesn't seem to be a way to create a cert without an image.

I think most of the times, one doesn't have images.

**Comment by vigasdeep** [comment]
I think this is mostly about the template we use. We should have have some space to view template features. Like currently we hover over image on home page, we see image preview. Likewise, there should be some space there, which shows the template features? what do you think?

**Comment by mandeeps708** [comment]
I think the same page would be good for this.

We need more templates. Then we may have categorization of the templates.

Template features... I think those should be seen by hovering or might be clicking a template may show more detail about it like how it looks and features.

**Comment by vigasdeep** [comment]
Keep this issue on least priority. Only after current templates are working properly, then implement this new template.

**Comment by amisha2016** [comment]
What we can do here is If USER accidentally miss to upload photo and click "generate button" then he will get an alert message like "If you do not upload an image, it will left empty on the certificate OK to continue". If he press OK then it will generate Certificate without photo.

**Comment by vigasdeep** [comment]
Okay, also make sure it works in other type of certificate generation Like with CSV data as well. Okay?

**Comment by amisha2016** [comment]
Okay
