### ISSUE TITLE
Unable to generate certificate

### ISSUE THREAD

**Issue by vigasdeep** [GreatDevelopers/Certificate#27]
```
[Sun Oct 01 20:16:04.546860 2017] [:error] [pid 31979] [client 117.247.42.16:10953] PHP Warning:  copy(odt/base/base59d14d04822c5.odt): failed to open stream: No such file or directory in /var/www/html/Certificate/library/odf.php on line 259, referer: http://developer.vigasdeep.com/Certificate/index.php?cert=design3
[Sun Oct 01 20:16:04.985870 2017] [:error] [pid 32474] [client 117.207.152.39:14073] PHP Warning:  copy(odt/base/base59d14d04ed9fb.odt): failed to open stream: No such file or directory in /var/www/html/Certificate/library/odf.php on line 259, referer: http://developer.vigasdeep.com/Certificate/index.php?cert=design3
[Sun Oct 01 20:16:24.823158 2017] [:error] [pid 31930] [client 117.207.152.39:14081] PHP Fatal error:  Uncaught OdfException: Nothing to parse - check that the content.xml file is correctly formed in /var/www/html/Certificate/library/odf.php:73\nStack trace:\n#0 /var/www/html/Certificate/manual.php(5): Odf->__construct('odt/base/base59...')\n#1 {main}\n  thrown in /var/www/html/Certificate/library/odf.php on line 73, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:18:02.456727 2017] [:error] [pid 31930] [client 117.247.42.16:10987] PHP Fatal error:  Uncaught OdfException: Nothing to parse - check that the content.xml file is correctly formed in /var/www/html/Certificate/library/odf.php:73\nStack trace:\n#0 /var/www/html/Certificate/manual.php(5): Odf->__construct('odt/base/base59...')\n#1 {main}\n  thrown in /var/www/html/Certificate/library/odf.php on line 73, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
```

**Comment by vigasdeep** [comment]
It is looking for a file which does not exist.

`PHP Warning:  copy(odt/base/base59d14d04822c5.odt): failed to open stream: No such file or directory 
`
There is no 'base' directory inside odt.

**Comment by vigasdeep** [comment]
Need to find why its looking for base/base59d14d04822c5.odt

**Comment by vigasdeep** [comment]
No permission issue. tried with 777, not working.

**Comment by vigasdeep** [comment]
created base dir inside odt/ and gave it required permission. Started working.

**Comment by vigasdeep** [comment]
another problem: can't see user image on crop screen, and cant move forward without cropping.

Errors in console:

```
[Sun Oct 01 20:42:00.803449 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  move_uploaded_file(uploads/manual/59d15318c421f1094477): failed to open stream: No such file or directory in /var/www/html/Certificate/manual.php on line 45, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.804337 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phppd0I2T' to 'uploads/manual/59d15318c421f1094477' in /var/www/html/Certificate/manual.php on line 45, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.804780 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagecreatefromjpeg(uploads/manual/59d15318c421f1094477): failed to open stream: No such file or directory in /var/www/html/Certificate/manual.php on line 55, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.805082 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagesx() expects parameter 1 to be resource, boolean given in /var/www/html/Certificate/manual.php on line 71, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.805290 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagesy() expects parameter 1 to be resource, boolean given in /var/www/html/Certificate/manual.php on line 72, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.805476 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagecreatetruecolor(): Invalid image dimensions in /var/www/html/Certificate/manual.php on line 75, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.805668 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagecopyresampled() expects parameter 1 to be resource, boolean given in /var/www/html/Certificate/manual.php on line 78, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual
[Sun Oct 01 20:42:00.805856 2017] [:error] [pid 31980] [client 117.247.42.16:11420] PHP Warning:  imagejpeg() expects parameter 1 to be resource, boolean given in /var/www/html/Certificate/manual.php on line 81, referer: http://developer.vigasdeep.com/Certificate/option.php?var=manual

```

**Comment by vigasdeep** [comment]
Fixed above by creating some folders. New error in error.log after generating.

`Error: Unable to connect or start own listener. Aborting.
`

**Comment by mandeeps708** [comment]
@vigasdeep try running the following manually:
$ `unoconv --listener`

**Comment by vigasdeep** [comment]
Yes, i tried that, did not work. ( I was root ) ..

Now tried the command with normal user, and yay! it worked.

**Comment by vigasdeep** [comment]
[59d1559f95e57.pdf](https://github.com/GreatDevelopers/Certificate/files/1347503/59d1559f95e57.pdf)
Finally. here's the certificate.  From my own personal installation.

**Comment by amisha2016** [comment]
Everything worked fine upto Generate Pdf Option. After that I encountered with an error.

Not Found

The requested URL /Certificate/pdf/59d27de9eb198.pdf was not found on this server.
Apache/2.4.18 (Ubuntu) Server at localhost Port 80

In /var/log/apache2/error.log file  The error displayed is
Unable to store document to file:///var/www/html/Certificate/pdf/59d27de9eb198.pdf (ErrCode 283)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x1ad6ba8{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"writer_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

**Comment by amisha2016** [comment]
The problem was with ownership of pdf folder. Its been solved now. The changed have been pushed into the restructured branch. So, I am going to close the issue.

**Comment by amisha2016** [comment]
@vigasdeep @mandeeps708 
Upload CSV File Section is not working in Restructured Branch.

[:error] [pid 3911] [client 127.0.0.1:54182] PHP Warning:  move_uploaded_file(uploads/csv/data/59d7368870556sample.csv): failed to open stream: No such file or directory in /var/www/html/Certificate/csv.php on line 31, referer: http://localhost/Certificate/option.php?var=csv

It seems that there is no directory csv/data inside uploads directory. That is why I reopened the issue.
